spring:
  datasource:
    url: jdbc:h2:mem:testdb
    # url: jdbc:h2:file:/data/demo
    driver-class-name: org.h2.Driver
    username: aleksey
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:

    console:
      enabled: true  # connect to: http://localhost:8080/h2-console

